wip

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -32,10 +32,19 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Debug package.json before get version
+        run: |
+          ls -l
+          cat package.json || echo "package.json not found"
+
       - name: Get version
         id: get_version
         run: |
           echo "version=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_OUTPUT
+
+      - name: Debug package.json after get version
+        run: |
+          cat package.json || echo "package.json not found"
 
       - name: Create release zip
         run: |
